@startuml
skinparam style strictuml
title Activity Diagram - Aktor Admin (Agri-POS)

|Admin|
start
:Login ke Sistem;

|Sistem Agri-POS|
:Validasi Akun & Role (Admin);
if (Akses Diberikan?) then (Ya)
  |Admin|
  split
    :Pilih Menu Manajemen Produk;
    |Sistem Agri-POS|
    :Tampilkan Daftar Produk;
    note right: Produk: Benih, Pupuk, Alat, Obat
    |Admin|
    :Lakukan Operasi CRUD;
    |Sistem Agri-POS|
    :Update Database Produk;
  split @plus
    |Admin|
    :Pilih Menu Laporan;
    |Sistem Agri-POS|
    :Proses Rekapitulasi Data;
    :Tampilkan Laporan Penjualan;
  end split
else (Tidak)
  |Sistem Agri-POS|
  :Tampilkan Pesan Error;
  stop
endif

|Admin|
:Logout;
stop
@enduml